# Generated by Django 2.1.2 on 2018-10-22 17:36

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_doctor', models.BooleanField(default=False)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('county', models.IntegerField(choices=[(1, 'Mombasa'), (2, 'Kwale'), (3, 'Kilifi'), (4, 'Tana River'), (5, 'Lamu'), (6, 'Taita Taveta'), (7, 'Moyale'), (8, 'Wajir'), (9, 'Garissa'), (10, 'Marsabit'), (11, 'Isiolo'), (12, 'Meru'), (13, 'Tharaka Nithi'), (14, 'Embu.'), (15, 'Kitui'), (16, 'Machakos'), (18, 'Makueni'), (19, 'Nyandarua'), (20, 'Nyeri'), (21, 'Kirinyaga'), (22, "Murang'a"), (23, 'Kiambu'), (24, 'Turkana'), (25, '.West Pokot'), (26, 'Samburu'), (27, 'Trans Nzoia'), (28, 'Uasin Gishu'), (29, 'Elgeyo / Marakwet'), (30, 'Nandi'), (31, 'Baringo'), (32, 'Laikipia'), (33, 'Nakuru'), (34, 'Narok'), (35, 'Kajiado'), (36, 'Kericho'), (37, 'Bomet'), (38, 'Kakamega'), (39, 'Vihiga'), (40, 'Bungoma'), (41, 'Busia'), (42, 'Siaya'), (43, 'Kisumu'), (44, 'Homa Bay'), (45, 'Migori'), (46, 'Kisii'), (47, 'Nyamira'), (48, 'Nairobi City')])),
                ('location', models.CharField(max_length=120, verbose_name='Place of residence')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.IntegerField(choices=[(0, 'MALE'), (1, 'FEMALE')])),
                ('bio', models.TextField(blank=True, null=True, verbose_name='User Biography')),
                ('qualifications', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('share_email', models.BooleanField(default=True, verbose_name='Share Your Email?')),
                ('share_address', models.BooleanField(default=True, verbose_name='Share Your Address')),
                ('share_phone', models.BooleanField(default=True, verbose_name='Share Your Address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'auth_user',
                'ordering': ['email', 'first_name', 'last_name'],
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
