# Generated by Django 2.1.2 on 2018-10-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20181022_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='random_password',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='User Autogen Keys'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.IntegerField(choices=[(1, 'Mombasa'), (2, 'Kwale'), (3, 'Kilifi'), (4, 'Tana River'), (5, 'Lamu'), (6, 'Taita Taveta'), (7, 'Moyale'), (8, 'Wajir'), (9, 'Garissa'), (10, 'Marsabit'), (11, 'Isiolo'), (12, 'Meru'), (13, 'Tharaka Nithi'), (14, 'Embu.'), (15, 'Kitui'), (16, 'Machakos'), (18, 'Makueni'), (19, 'Nyandarua'), (20, 'Nyeri'), (21, 'Kirinyaga'), (22, "Murang'a"), (23, 'Kiambu'), (24, 'Turkana'), (25, '.West Pokot'), (26, 'Samburu'), (27, 'Trans Nzoia'), (28, 'Uasin Gishu'), (29, 'Elgeyo / Marakwet'), (30, 'Nandi'), (31, 'Baringo'), (32, 'Laikipia'), (33, 'Nakuru'), (34, 'Narok'), (35, 'Kajiado'), (36, 'Kericho'), (37, 'Bomet'), (38, 'Kakamega'), (39, 'Vihiga'), (40, 'Bungoma'), (41, 'Busia'), (42, 'Siaya'), (43, 'Kisumu'), (44, 'Homa Bay'), (45, 'Migori'), (46, 'Kisii'), (47, 'Nyamira'), (48, 'Nairobi City')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=120, null=True, verbose_name='Place of residence'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='share_address',
            field=models.BooleanField(default=False, verbose_name='Share Your Address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='share_email',
            field=models.BooleanField(default=False, verbose_name='Share Your Email?'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='share_phone',
            field=models.BooleanField(default=False, verbose_name='Share Your Address'),
        ),
    ]
