# Generated by Django 2.1.2 on 2018-11-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20181102_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
