# Generated by Django 2.1.2 on 2018-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
