# Generated by Django 2.1.2 on 2018-11-01 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='book_time',
            field=models.TimeField(null=True, verbose_name='Appointment Time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='county',
            field=models.IntegerField(choices=[(1, 'Mombasa'), (2, 'Kwale'), (3, 'Kilifi'), (4, 'Tana River'), (5, 'Lamu'), (6, 'Taita Taveta'), (7, 'Moyale'), (8, 'Wajir'), (9, 'Garissa'), (10, 'Marsabit'), (11, 'Isiolo'), (12, 'Meru'), (13, 'Tharaka Nithi'), (14, 'Embu.'), (15, 'Kitui'), (16, 'Machakos'), (18, 'Makueni'), (19, 'Nyandarua'), (20, 'Nyeri'), (21, 'Kirinyaga'), (22, "Murang'a"), (23, 'Kiambu'), (24, 'Turkana'), (25, '.West Pokot'), (26, 'Samburu'), (27, 'Trans Nzoia'), (28, 'Uasin Gishu'), (29, 'Elgeyo / Marakwet'), (30, 'Nandi'), (31, 'Baringo'), (32, 'Laikipia'), (33, 'Nakuru'), (34, 'Narok'), (35, 'Kajiado'), (36, 'Kericho'), (37, 'Bomet'), (38, 'Kakamega'), (39, 'Vihiga'), (40, 'Bungoma'), (41, 'Busia'), (42, 'Siaya'), (43, 'Kisumu'), (44, 'Homa Bay'), (45, 'Migori'), (46, 'Kisii'), (47, 'Nyamira'), (48, 'Nairobi City')], help_text='From which county does the patient comes from', null=True, verbose_name='County of Residence'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.IntegerField(choices=[(0, 'CONSULTATION'), (2, 'DIAGNOSTICS'), (3, 'ENT'), (4, 'DERMATOLOGY'), (6, 'GENERAL CHECKUP'), (7, 'DENTIST'), (8, 'NUTRITIONIST')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='book_date',
            field=models.DateField(verbose_name='Appointement Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.CharField(blank=True, help_text='Current Location', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
