# Generated by Django 2.1.2 on 2018-11-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20181101_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.IntegerField(choices=[(0, 'CONSULTATION'), (2, 'DIAGNOSTICS'), (3, 'ENT'), (4, 'DERMATOLOGY'), (6, 'GENERAL CHECKUP'), (7, 'DENTIST'), (8, 'NUTRITIONIST')], help_text='Appointment Speciality'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='book_date',
            field=models.DateField(help_text='Date of Appointment', verbose_name='Appointement Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='book_time',
            field=models.IntegerField(choices=[(0, '08:00-9:30'), (1, '09:30-10:30'), (2, '10:30-11:30'), (3, '11:30-12:30'), (4, '12:30-1:30'), (5, '1:30-2:30'), (6, '2:30-3:30'), (7, '3:30-4:30'), (8, '4:30-5:00')], help_text='Time of the appointment', null=True, verbose_name='Appointment Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(help_text='Enter patient full names', max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_phone',
            field=models.CharField(help_text='Patient Contacts', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='severity_level',
            field=models.IntegerField(choices=[(0, 'MILD'), (1, 'HIGH'), (2, 'EMERGENCY')], help_text='Appointment Severity/Urgench'),
        ),
    ]
