# Generated by Django 2.1.2 on 2018-11-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20181101_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='book_time',
            field=models.IntegerField(choices=[(0, '08:00-9:30 am'), (1, '09:30-10:30 am'), (2, '10:30-11:30 am'), (3, '11:30-12:30 pm'), (4, '12:30-1:30 pm'), (5, '1:30-2:30 pm'), (6, '2:30-3:30 pm'), (7, '3:30-4:30 pm'), (8, '4:30-5:00 pm')], help_text='Time of the appointment', null=True, verbose_name='Appointment Time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointments', to='hospitals.Hospital'),
        ),
    ]
