# Generated by Django 2.1.2 on 2018-11-02 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20181102_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='other_hospitals',
            field=models.CharField(blank=True, help_text='IF patient prefers linking to other facilitis', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctors',
            field=models.ForeignKey(help_text='Our Proffessional Doctors', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_docs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(help_text='Only if the patient prefers this facility', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_appointments', to='hospitals.Hospital'),
        ),
    ]
