# Generated by Django 2.1.2 on 2018-11-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20181102_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='other_hospitals',
            field=models.IntegerField(blank=True, choices=[(0, 'OMBO MISSION HOSPITAL'), (1, 'MIGORI COUNTY TEACHING AND REFERAL HOSPITAL'), (2, 'OASIS MEDICAL CLINIC')], help_text='IF patient prefers linking to other facilitis', null=True),
        ),
    ]
