# Generated by Django 2.1.2 on 2018-11-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20181103_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='admin@gmail.net', help_text='Patient Email', max_length=254),
            preserve_default=False,
        ),
    ]
