# Generated by Django 2.1.2 on 2018-11-17 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_auto_20181107_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date_seen',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
