DISEASES =(('AirBorne Disease',(('CmC','Common Cold'),('Inf','Influenza'),('Cp','ChickenPox'),('Mps','Mumps'),('Msl','Measels'),
                                ('TB','Tuberculosis'),('WPC','Whooping Cough(Pertussis)'))),
            (u'Cancer', ((u'BoC', u'Bone Cancer'), (u'BrC', u'Brain Cancer'), (u'BrC', u'Breast Cancer'), (u'ColC', u'Colon Cancer'),
                        (u'CrC', u'Colorectal Cancer'), (u'EsC', u'Esophageal Cancer'), (u'FAP', u'Familial adnenomatous polyposis (FAP)'),
                        (u'GaC', u'Gastric Cancer'), (u'HnpcC', u'Lynch Syndrome/Hereditary non-polyposis colorectal cancer (HNPCC)'),
                        (u'KiC', u'Kidney Cancer'), (u'Leu', u'Leukemia'), (u'LiC', u'Liver Cancer'), (u'LuC', u'Lung Cancer'),
                        (u'MuC', u'Muscle Cancer'), (u'OtC', u'Other Cancer'), (u'OvC', u'Ovarian Cancer'), (u'PnC', u'Pancreatic Cancer'),
                        (u'PrC', u'Prostate Cancer'), (u'ReC', u'Rectal Cancer'), (u'SkC', u'Skin Cancer'), (u'ThC', u'Thyroid Cancer'),
                        (u'UnC', u'Unknown Cancer'), (u'UtC', u'Uterine Cancer'))
            ),
           ('Conditions',(('ACN','ACNE'),('ASM','ASTHMA'),('ATH','ATHEROSCLEROS'),('BF','BONE FRACTURE'),
                          ('BNs','BURNS'),('CONST','CONSTIPATION'),('CH','COUGH'),('CTs','CUTS'),
                          ('DeP','DEPRESSION(Melancholia)'), ('HED','HEADACHES'),('INDEG','INDIGESTION'),('INsM','INSOMNIA'),
                          ('JN','JAUNDICE'),('LUM','LUMBAGO(LOW BACK PAIN)'),('MEN','MENSTRUAL PROBLEMS'),('MIG','MIGRAINES'),
                          ('MonS','MORNING SICKNESS'),('NR','NEURALGIA'),('Ps','POISONING'),('SPns','SPRAINS'), ('Stn','STINGS'),
                          ('StMa','STOMACHACHE'),('Ulc','ULCERS'),('Wts','WARTS'))),
           (u'Clotting Disorder', ((u'ClD', u'Clotting Disorder'), (u'DVT', u'Deep Vein Thrombosis (DVT)'),
                                   (u'PuE', u'Pulmonary Embolism'),
                                   (u'UCD', u'Unknown Clotting Disorder'))),
           (u'Dementia/Alzheimers', ((u'Alz', u"Dementia/Alzheimer's"),('UDM','Unknown Dementia/Alzheimers'))),
           (u'Diabetes', ((u'DIAB', u'Diabetes'), (u'Gest', u'Gestational Diabetes'), (u'IFG', u'Impaired Fasting Glucose'),
                          (u'IGT', u'Impaired Glucose Tolerance'), (u'INR', u'Insulin Resistance'),
                          (u'MODY', u'Maturity Onset Diabetes mellitus in Young (MODY)'), (u'PreD', u'Pre-Diabetes'),
                          (u'DIA1', u'Type 1 Diabetes'), (u'DIA2', u'Type 2 Diabetes'), (u'UDI', u'Unknown Diabetes'))),
           (u'Gastrointestinal Disorder', ((u'GI', u'Colon Polyp'), (u'Crd', u"Crohn's Disease"),
                                           (u'FAP', u'Familial adnenomatous polyposis (FAP)'),
                                           (u'GI', u'Gastrointestinal Disorder'), (u'IBS', u'Irritable Bowel Syndrome'),
                                           (u'HnpcC', u'Lynch Syndrome/Hereditary non-polyposis colorectal cancer (HNPCC)'),
                                           (u'Ulc', u'Ulcerative Colitis'), (u'UGI', u'Unknown Gastrointestinal Disorder'))),
           (u'Heart Disease', ((u'AP', u'Angina'), (u'CAD', u'Coronary Artery Disease'), (u'HA', u'Heart Attack'),
                               (u'HD', u'Heart Disease'),('EH','Enlarged Heart (Cardiomegaly)'),('IHR','Irregular heart rhythm'),
                               ('AF','Atrial Fibrillation'),('HVD','Heart Valve Disease'),('SCD','Sudden Cardiac Death'),
                               ('CHD','Congenital Heart Disease'),('DC','Dilated Cardiomyopathy'),
                               ('HCM','Hypertrophic Cardiomyopathy'),('RCM','Restrictive cardiomyopathy'),('Pcd','Pericarditis'),
                               ('PCF','Pericardial Effusion'),('MafS','Marfan Syndrome'),('HrM','Heart Murmurs'),
                               (u'UHD', u'Unknown Heart Disease'))),
           ('Hepatitis',(('HPA','Hepatitis A'),('HPB','Hepatitis B'),('HPC','Hepatitis C'),('HPD','Hepatitis D'),
                         ('HPE','Hepatitis E'))),
           (u'High Cholesterol',((u'HCH', u'High Cholesterol'),('other','Other Cholestoral Related'))),
           (u'Hypertension', ((u'HYP', u'Hypertension'),('other','Other Hypertesion Related'))),
           (u'Kidney Disease', ((u'CKD', u'Cystic Kidney Disease'), (u'DkD', u'Diabetic Kidney Disease'),
                                (u'CongKD', u'Kidney Disease Present from Birth'), (u'KN', u'Kidney Nephrosis'),
                                (u'Nep', u'Nephritis'), (u'OKD', u'Other Kidney Disease'),('HMD','Heart Muscle Disease (Cardiomyopathy)'),
                                ('DlC',''),
                                (u'UKD', u'Unknown Kidney Disease'))
            ),
           (u'Lung Disease', ((u'Ast', u'Asthma'), (u'LD', u'COPD'), (u'ChrB', u'Chronic Bronchitis'),
                              (u'CDRS', u'Chronic Lower Respiratory Disease'), (u'Emp', u'Emphysema'),
                              (u'InP', u'Influenza/Pneumonia'), (u'LD', u'Lung Disease'),
                              (u'ULD', u'Unknown Lung Disease'))),
           (u'Malaria',(('PF','Plasmodium falciparum'),('PV','Plasmodium vivax'),('PM','Plasmodium malariae'),
                        ('PO','Plasmodium ovale'),('PK','Plasmodium knowlesi'))),
           (u'Osteoporosis', ((u'OST', u'Osteoporosis'),('other','Other Osteoporosis Related'))),
           (u'Psychological Disorder', ((u'Anx', u'Anxiety'), (u'ADHA', u'Attention Deficit Disorder-Hyperactivity'),
                                        (u'Aut', u'Autism'), (u'Bmd', u'Bipolar Disorder'), (u'Dem', u'Dementia'),
                                        (u'Dep', u'Depression'),
                                        (u'ED', u'Eating Disorder'), (u'MD', u'Mental Disorder Unspecified'),
                                        (u'OCD', u'Obsessive Compulsive Disorder'), (u'PaD', u'Panic Disorder'),
                                        (u'PcD', u'Personality Disorder'), (u'PTSD', u'Post Traumatic Stress Disorder'),
                                        (u'MD', u'Schizophrenia'), (u'Soc', u'Social Phobia'),
                                        (u'UPD', u'Unknown Psychological Disorder'))),
           (u'Septicemia', ((u'Sept', u'Septicemia'), ('USEP','Unknown Septicemia Disease'))),
           (u'Stroke/Brain Attack', ((u'SBA', u'Stroke/Brain Attack'),('USBA','Unkonwn Stroke/Brain Attack'))),
           (u'Sudden Infant Death Syndrome', ((u'SIDS', u'Sudden Infant Death Syndrome'),
                                              ('USIDS','Unknown Sudden Infant Death Syndrome'))),
           (u'Water Bone Disease', (('PL','Polio'),('CH','Cholera'), ('DN','Dengue'),('SC', 'Scabies'),('TF','Typhoid'),
                                    ('AM','Anaemia'),('BT', 'Botulism'),('FL', 'Fluorosis'),('TR','Trachoma'),
                                    ('DP','Diarrhea'),('GA','Giardiasis'),('AS','Ascariasis'),('TrC','Trichuriasis'),('ArS', 'Arsenicosis'),
                                    ('ML','Malnutrition'), ('LG','Legionellosis'),('LeP', 'Leptospirosis'),('SC','Schistomiasis'),
                                    ('DrC','Dracunculiasis'), ('OnC','Onchocerciasis'), ('LeP','Lead poisoning'), ('CrP','Cryptosporiodiosis'),
                                    ('CmL','Campylobacteriosis'), ('LyF','Lymphatic filarasis') ,('HkI','Hookworm infection'),
                                    ('RWT','Ring Worm or Tinea'),('MeT','Methaemoglobinemia'), ('CyT','Cyanobacterial toxins'),
                                    ('JaP','Japanese encephalitis')
                                  )
           )
        )
