# Generated by Django 2.1.2 on 2018-10-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('head', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_head', to=settings.AUTH_USER_MODEL)),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
