# Generated by Django 2.1.2 on 2018-10-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Clinic', 'verbose_name_plural': 'Clinics'},
        ),
    ]
