# Generated by Django 2.1.2 on 2018-11-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='is_seen',
            field=models.BooleanField(default=False, help_text='Whether the emergency has been cleared or not'),
        ),
    ]
