# Generated by Django 2.1.2 on 2018-10-19 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('sickness_period', models.CharField(help_text='For how long have you been sick?', max_length=100)),
                ('symptioms', models.TextField(help_text='What symptoms are you experiencing?')),
                ('other_info', models.TextField(help_text='Other revelant information')),
                ('any_medication', models.BooleanField(default=False, help_text='Has the patient taken any medication before this')),
                ('medication', models.CharField(max_length=250, null=True)),
                ('results', models.TextField(help_text='Result of the diagnosis given as a feedback to the patient', null=True)),
                ('prescription', models.TextField(null=True)),
                ('diatery_advice', models.TextField(null=True)),
                ('medical_advice', models.TextField(null=True)),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='diseases.Diseases')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='hospitals.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emergencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('category', models.IntegerField(choices=[(0, 'ACCIDENT'), (1, 'POISONING'), (2, 'CHILD BIRTH'), (3, 'OTHER')])),
                ('full_names', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('nearest_health_center', models.CharField(max_length=200, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='hospitals.Hospital')),
            ],
        ),
    ]
