# Generated by Django 2.1.2 on 2018-11-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20181022_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencies',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Emergencies',
        ),
    ]
