# Generated by Django 2.1.2 on 2018-11-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_auto_20181103_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='audio_clip',
            field=models.FileField(blank=True, null=True, upload_to='treatements/audio/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatements/images/'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to='treatements/video/'),
        ),
    ]
