# Generated by Django 2.1.2 on 2018-11-07 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_auto_20181107_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='any_medication',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='medication',
        ),
        migrations.AddField(
            model_name='consultation',
            name='previous_medication',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Have you taken any medication? If yes, name the medication'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='diseases.Diseases', verbose_name='Sickness category'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='other_info',
            field=models.TextField(blank=True, null=True, verbose_name='Any Other revelant information?'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='sickness_period',
            field=models.CharField(max_length=100, verbose_name='For how long have you been sick?'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(verbose_name='What symptoms are you experiencing?'),
        ),
    ]
