# Generated by Django 2.1.2 on 2018-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_auto_20181107_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='sickness_period',
            field=models.IntegerField(choices=[(0, '12-24 HOURS'), (1, '24-48 HOURS'), (2, '2-4 DAYS'), (3, '1-2 WEEKS'), (4, '2-3 WEEKS'), (5, 'LESS THAN A MONTH'), (6, '1-2 MONTHS'), (7, '2-3 MONTHS'), (8, '3-4 MONTHS'), (9, '4-5 MONTHS'), (10, '5-7 MONTHS'), (11, '8-10 MONTHS'), (12, 'LESS THAN A YEAR'), (13, 'LESS THAN 2 YEARS'), (14, 'MORE THAN 2 YEARS')], verbose_name='For how long have you been sick?'),
        ),
    ]
