# Generated by Django 2.1.2 on 2018-11-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_auto_20181107_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='previous_medication',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Have you taken any medication? If yes, kindly name the medication'),
        ),
    ]
