# Generated by Django 2.1.2 on 2018-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0010_auto_20181110_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='audio_clip',
            field=models.FileField(blank=True, null=True, upload_to='treatements/audio/', verbose_name='Assisting Audio Clip'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treatements/images/', verbose_name='Assisting Picture'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='video_clip',
            field=models.FileField(blank=True, null=True, upload_to='treatements/video/', verbose_name='Assisting Video Clip'),
        ),
    ]
