# Generated by Django 2.1.2 on 2018-11-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0012_auto_20181111_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='drugs',
            field=models.TextField(help_text='Drugs recommended for the patient', null=True, verbose_name='Recommend Drugs'),
        ),
    ]
