# Generated by Django 2.1.2 on 2018-11-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0013_consultation_drugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='disease',
            field=models.CharField(max_length=500, null=True, verbose_name='Confirmed Sickness'),
        ),
    ]
