# Generated by Django 2.1.2 on 2018-11-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0014_auto_20181113_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='patient',
            new_name='appointment',
        ),
        migrations.AddField(
            model_name='consultation',
            name='new_patient',
            field=models.CharField(help_text='If patient never booked an appointment, consider new', max_length=255, null=True),
        ),
    ]
