# Generated by Django 2.1.2 on 2018-11-17 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_auto_20181116_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='new_patient',
            field=models.ForeignKey(help_text='If patient never booked an appointment and has to be treated directly, consider new patient but has to register', max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
