# Generated by Django 2.1.2 on 2018-11-17 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0016_auto_20181117_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='date_cleared',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='new_patient',
            field=models.ForeignKey(blank=True, help_text='If patient never booked an appointment and has to be treated directly, consider new patient but has to register', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
